apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-finder
  labels:
    app: hotel-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-finder
  template:
    metadata:
      labels:
        app: hotel-finder
    spec:
      containers:
      - name: hotel-finder
        image: gcr.io/sigma-sector-384007/ascenda:latest
        ports:
        - containerPort: 8080
